{% set version = "1.5-3" %}

package:
  name: r-sn
  version: {{ version|replace("-", "_") }}

source:
  fn: sn_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/sn_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/sn/sn_{{ version }}.tar.gz
  sha256: cc21b97ddd674c9b1296260f2a72ffb085cdcb877c8332f0bfa96ff028517183

build:
  noarch: generic
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-mnormt >=1.5_4
    - r-numderiv

  run:
    - r-base
    - r-mnormt >=1.5_4
    - r-numderiv

test:
  commands:
    - $R -e "library('sn')"  # [not win]
    - "\"%R%\" -e \"library('sn')\""  # [win]

about:
  home: http://azzalini.stat.unipd.it/SN
  license: GPL-2 | GPL-3
  summary: Build and manipulate probability distributions of the skew-normal  family and some
    related ones, notably the skew-t family, and provide related statistical methods
    for data fitting and diagnostics, in the univariate and  the multivariate case.
  license_family: GPL

extra:
  recipe-maintainers:
    - dpryan79
    - bgruening
    - daler
    - johanneskoester
    - rvalieris
