{% set version = "2.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sn
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sn_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sn/sn_{{ version }}.tar.gz
  sha256: f9f6b56d91dc7cb18dc8308d0875b9648c90b268d1aaf8f4c5164ff016df22bd

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mnormt >=2.0.0
    - r-numderiv
    - r-quantreg
  run:
    - r-base
    - r-mnormt >=2.0.0
    - r-numderiv
    - r-quantreg

test:
  commands:
    - $R -e "library('sn')"           # [not win]
    - "\"%R%\" -e \"library('sn')\""  # [win]

about:
  home: http://azzalini.stat.unipd.it/SN
  license: GPL-2.0-or-later
  summary: Build and manipulate probability distributions of the skew-normal family and some related ones, notably the skew-t family, and provide related statistical methods for data fitting and model diagnostics, in the univariate and the multivariate case.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - rvalieris

# Package: sn
# Version: 1.6-0
# Date: 2020-03-28
# Title: The Skew-Normal and Related Distributions Such as the Skew-t
# Authors@R: person(given = "Adelchi", family = "Azzalini", email = "adelchi.azzalini@unipd.it", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-7583-1269"))
# Maintainer: Adelchi Azzalini <adelchi.azzalini@unipd.it>
# Depends: R (>= 2.15.3), methods, stats4
# Imports: mnormt (>= 1.5-4), numDeriv, utils, quantreg
# Description: Build and manipulate probability distributions of the skew-normal family and some related ones, notably the skew-t family, and provide related statistical methods for data fitting and model diagnostics, in the univariate and the multivariate case.
# License: GPL-2 | GPL-3
# URL: http://azzalini.stat.unipd.it/SN
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2020-03-28 07:33:15 UTC; aa
# Author: Adelchi Azzalini [aut, cre] (<https://orcid.org/0000-0002-7583-1269>)
# Repository: CRAN
# Date/Publication: 2020-03-28 09:50:02 UTC
