appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: fTp7HPL3VfE/weAGKkGRIuWZKKpS7YTHJpYNX3gdD5O3vQI9JsM6Wdq7eczTYvgqGIBttEe4EYZuox5TnzxYUS1Wt9c7hNfryFzL20HEOI9ePz7QMrT995nIItIi+zgEtXIqGLcp4jPuX+bTnBgxhJrMaN6e3C/l5YVTjsooIVAyoyl7ASGpqe4WGnuYpX/Rni/irnVkBaKU0cUXvXtx752EjQC+bXbcyvFtGXqz0H6QfQwBdCG2gYYTworG1BjpPrELYGCXjH6rsAtCqB05FTxmRXCHa7W++DKDswWqfpjcIpkFqfPwgjIvWgZV/0s2diMsOd+c0l6yrAlyz66wbvUC3veJGM96NJzFqO2gdTTnH6vF4A1c3/VzkZxBHJAWJGa0HBmzeVjUrOwWrwBmljelOg2Z3gAPbMcWYQSY6RVKN93R6urhNC8DM2VIlESJyUmd+Z0Ste6N/jNSCrn/mc0w5+E/c0qofA0qnN9C5Ig1cOdH1oszZe+wvB/L1XhxWfHt29BbRFW/hibr5NUrxh7PrPp3ove2QrH/b3l55zM+vOXhtZA+QMpG2/Gwkdsoejn+loG85zwdSc0spFHYByiKYa6wPOS7cdwH49PyQ2e3PVThCGDs9mAJUjZV9wRoJZFsd6zc54gWZewSQaQA3SMVXvNlXBpojvD39PTGYlQ=
conda_forge_output_validation: false
