travis:
  secure:
    BINSTAR_TOKEN: aX/a2A3laYP9jKSTmwshH7rkvYX7LQDJbWvc+G6SOfgWhBF3xBpDQzc4ohwKAouIl265h+VTydmRj6WMSGTE9LCZrXLLSMzBfOg4w6D2bk82VTqr6gjpSg+y/iIfGkDCksSYMYJQcUMrL7zMDZKvlqEvcc4I6o+gnWJkzmxfHkEkDhiRbRF81xKDQYqF2zfif91HZaGhYZNnF7z9TzbQxTqM5Xv0inl7ON4Kf7coP8shcuRHkQYET7xxKpyaOpi1lBo2lpAzJa390dih9lTTMF9K/BbIZ6NkzszxFKEcqrkMoRprGpWMdvl23kRvN3j2dkZO+VtmOvGodIlKq9gbVQU84cAeeARIn92dlR9EAmS4oqCAHhbJ/jElrV3HsKl6cbwp7T4bXyFJv/OMvZhZzgnD/sDsGG5F6DTMnx5x04HZ0PNvsVWFlRwGYBK9p0kuxGMPN/8cSr4iY+j+vki/RCAXAyuCv31X2iE7SZuq7tguRd4TW5uG8rhQMTYiDZLS/KjhBJQ3eBGgjONT79W7OGpkQSkP3dtRRh+J4P0S9rbVMvLnPBPC+ORViz0WiUV7tKILGMe7kp5+ejzdR8RpEsnH+0wU1b0h3ozPkh4Zl7HLKWOjz0ocOyejWqZKJTSTIBqvBl8+27Oezk5iPDgYwUkc5xMiEM6MR/h0mEUZ5Js=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
